version: '3'
services:
  web:
    image: registry.pinnacleseven.com/bapps/pinnacle-odoo-docker:odoo17-16
    depends_on:
      - postgres
    environment:
      - HOST=postgres  # Change this from 'db' to 'postgres'
      - USER=wakatech
      - PASSWORD=wakatech
    ports:
      - "8070:8069"
    volumes:
      - wakatech-dev-web-data:/var/lib/odoo
      - /home/ubuntu/dev/Accounting/addons:/odoo/custom-addons
      - /home/ubuntu/dev/Accounting/entp-addons:/odoo/entp-addons
    command: -d waka_04112024 -u all
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=wakatech
      - POSTGRES_USER=wakatech
      - PGDATA=/var/lib/postgresql/data/pgdata_new
    ports:
      - "5434:5432"
    volumes:
      - /opt/odoo/dbwakatech-data:/var/lib/postgresql/data/pgdata

volumes:
  wakatech-dev-web-data:
